name: icepeak-client
version: '0.0.1'
synopsis: Client library for Icepeak, a fast JSON document store with push notification support
license: BSD3
homepage: https://github.com/channable/icepeak

ghc-options: >-
  -Wall
  -Wincomplete-uni-patterns
  -Wincomplete-record-updates

dependencies:
  - base >= 4.9.1.0 && < 4.10

library:
  source-dirs: src
