---
resources:
- name: icepeak-src
  type: git
  source:
    uri: https://github.com/channable/icepeak
    branch: concourse

jobs:

- name: build
  plan:
  - get: icepeak-src
    trigger: true

  - task: build
    file: icepeak-src/server/ci/stack.yml
    vars: { "args": "build" }

  - task: test
    file: icepeak-src/server/ci/stack.yml
    vars: { "args": "test" }
