version: 2.0
jobs:
  build:
    docker:
      - image: "ubuntu:bionic"
    steps:
      - checkout
      - run:
          name: "install curl"
          command: |
            apt update
            apt install -y curl build-essential libgmp-dev
      - run:
          name: "install stack"
          command: |
            curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C /usr/local/bin '*/stack'
      - run:
          name: "print debug info"
          command: |
            echo $PATH
            pwd
            stack --version
      - run:
          name: "build server"
          command: "stack build -j2 --no-terminal"
          working_directory: "/root/project/server"
      - run:
          name: "test server"
          command: "stack test -j2 --no-terminal"
          working_directory: "/root/project/server"
      - run:
          name: "build client"
          command: "stack build -j2 --no-terminal"
          working_directory: "/root/project/client-haskell"
      - run:
          name: "test cliient"
          command: "stack test -j2 --no-terminal"
          working_directory: "/root/project/client-haskell"
