version: 2.0
jobs:
  build:
    docker:
      - image: "ubuntu:bionic"
    steps:
      - checkout
      - run:
          name: "install stack"
          commands:
            - "mkdir -p ~/.local/bin"
            - "export PATH=$HOME/.local/bin:$PATH"
            - "curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'"
      - run:
          name: "stack version"
          command: "stack --version"
