version: 2.0
jobs:
  build:
    docker:
      - image: "ubuntu:bionic"
    steps:
      - checkout
      - run:
          name: "install curl"
          command: |
            apt install curl
      - run:
          name: "install stack"
          command: |
            mkdir -p ~/.local/bin
            curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      - run:
          name: "debug path"
          command: "echo $PATH"
      - run:
          name: "stack version"
          command: "stack --version"
