version: 2.0
jobs:
  build:
    docker:
      - image: "ubuntu:bionic"
    steps:
      - checkout
      - run:
          name: "install curl"
          command: |
            apt update
            apt install -y curl
      - run:
          name: "install stack"
          command: |
            curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C /usr/local/bin '*/stack'
      - run:
          name: "print debug info"
          command: |
            echo $PATH
            pwd
            stack --version
