version: 2.1
jobs:
  build:
    docker:
      - image: "ubuntu:bionic"
    steps:
      - checkout
      - run:
          name: "install apt dependencies"
          command: |
            apt update
            apt install --no-install-recommends -y curl build-essential libgmp-dev zlib1g zlib1g-dev
      - run:
          name: "install stack"
          command: |
            curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C /usr/local/bin '*/stack'
      - run:
          name: "print debug info"
          command: |
            echo $PATH
            pwd
            stack --version
      - restore_cache:
          name: "restore server"
          keys:
            - icepeak-server-{{ checksum "server/package.yaml" }}-{{ checksum "server/stack.yaml" }}
      - restore_cache:
          name: "restore client"
          keys:
            - icepeak-client-{{ checksum "client-haskell/package.yaml" }}-{{ checksum "client-haskell/stack.yaml" }}
      - restore_cache:
          name: "restore client"
          keys:
            - icepeak-ghc-{{ checksum "server/stack.yaml" }}-{{ checksum "client-haskell/stack.yaml" }}
      - run:
          name: "build server"
          command: "stack build -j2 --no-terminal"
          working_directory: "/root/project/server"
      - run:
          name: "test server"
          command: "stack test -j2 --no-terminal"
          working_directory: "/root/project/server"
      - run:
          name: "build client"
          command: "stack build -j2 --no-terminal"
          working_directory: "/root/project/client-haskell"
      - run:
          name: "test client"
          command: "stack test -j2 --no-terminal"
          working_directory: "/root/project/client-haskell"
      - save_cache:
          name: "server cache"
          key: icepeak-server-{{ checksum "server/package.yaml" }}-{{ checksum "server/stack.yaml" }}
          paths:
            - "server/.stack-work"
      - save_cache:
          name: "client cache"
          key: icepeak-client-{{ checksum "client-haskell/package.yaml" }}-{{ checksum "client-haskell/stack.yaml" }}
          paths:
            - "client-haskell/.stack-work"
      - save_cache:
          name: "ghc cache"
          key: icepeak-ghc-{{ checksum "server/stack.yaml" }}-{{ checksum "client-haskell/stack.yaml" }}
          paths:
            - "/root/.stack"
