steps:
  - command: |
      mkdir -p ~/.local/bin
      export PATH=$HOME/.local/bin:$PATH
      curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    label: "Before install"

  - wait

  - command: |
      (cd server && stack setup -j8 --no-terminal)
      (cd client-haskell && stack setup -j8 --no-terminal)
    label: "Install the compiler"

  - wait

  - command: |
      (cd server && stack build -j8 --no-terminal)
      (cd server && stack test  -j8 --no-terminal)
      (cd client-haskell && stack build -j8 --no-terminal)
      (cd client-haskell && stack test  -j8 --no-terminal)
      echo "Finished the build"
    label: "Run build and tests"
