---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: haskell

inputs:
- name: icepeak-src

run:
  dir: icepeak-src/server
  #path: icepeak-src/server/ci/build.sh
  path: ls
  #args: ((args))
