---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: haskell

run:
  dir: icepeak-src/server
  path: ci/stack.sh
  args: ((args))

caches:
- path: stack-root
- path: icepeak-src/server/.stack-work
