---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: haskell

inputs:
- name: icepeak-src
- name: stack-root
  optional: true
- name: stack-work
  optional: true

outputs:
- name: stack-root
- name: stack-work

run:
  dir: icepeak-src/server
  path: ci/stack.sh
  args: ((args))

caches:
- path: stack-root
