name: icepeak
version: '0.0.1'
synopsis: Icepeak is a fast Json document store with push notification support
license: BSD3
homepage: https://github.com/channable/icepeak
ghc-options:
- -Wall
- -Werror

dependencies:
- aeson >=1.1 && <1.2
- async >=2.1 && <2.2
- base >=4.8 && <5.0
- bytestring >=0.10 && <0.11
- containers >=0.5 && <0.6
- directory >= 1.3 && <1.4
- hashable >=1.2 && <1.3
- http-types >=0.9 && <0.10
- jwt >= 0.7 && <0.8
- monad-logger >=0.3 && <0.4
- mtl >=2.2 && <2.3
- network >=2.6 && <2.7
- optparse-applicative >= 0.13 && <0.14
- random >=1.1 && <1.2
- scotty >=0.11 && <0.12
- stm >=2.4 && <2.5
- text >=1.2 && <1.3
- time >= 1.6 && <1.7
- unix >=2.7 && <2.8
- unordered-containers >=0.2 && <0.3
- uuid >=1.3 && <1.4
- wai >=3.2 && <3.3
- wai-extra >=3.0 && <3.1
- wai-websockets >=3.0 && <3.1
- warp >=3.2 && <3.3
- websockets >=0.12 && <0.13
- securemem <0.2

library:
  source-dirs: src
  ghc-options:
  - -Wno-orphans
  - -Wno-unused-top-binds
  - -O2
  - -fno-ignore-asserts
  - -funbox-strict-fields
  exposed-modules:
  - AccessControl
  - Config
  - Core
  - HttpServer
  - JwtAuth
  - JwtMiddleware
  - Logger
  - Server
  - Store
  - Subscription
  - WebsocketServer

executables:
  icepeak:
    main: Icepeak.hs
    source-dirs: app
    ghc-options:
    - -O2
    - -threaded
    - ! '"-with-rtsopts=-N -I0"'
    dependencies:
    - icepeak

  icepeak-token-gen:
    main: IcepeakTokenGen.hs
    source-dirs: app
    dependencies:
    - icepeak

tests:
  spec:
    main: Spec.hs
    source-dirs: tests
    ghc-options:
    - -Wno-orphans
    dependencies:
    - hspec >=2.4 && <2.5
    - hspec-core >=2.4 && <2.5
    - hspec-expectations >=0.8 && <0.9
    - QuickCheck >=2.9 && <2.10
    - quickcheck-instances >=0.3 && <0.4
    - icepeak
