name: icepeak
version: '0.6.1'
synopsis: Icepeak is a fast JSON document store with push notification support
license: BSD3
homepage: https://github.com/channable/icepeak
ghc-options:
- -Wall
- -Werror

dependencies:
- aeson
- async
- base
- bytestring
- containers
- directory
- hashable
- http-types
- jwt
- monad-logger
- mtl
- network
- optparse-applicative
- prometheus-client
- prometheus-metrics-ghc
- random
- scotty
- stm
- text
- time
- unix
- unordered-containers
- uuid
- wai
- wai-extra
- wai-middleware-prometheus
- wai-websockets
- warp
- websockets
- securemem

library:
  source-dirs: src
  ghc-options:
  - -Wno-orphans
  - -Wno-unused-top-binds
  - -O2
  - -fno-ignore-asserts
  - -funbox-strict-fields
  exposed-modules:
  - AccessControl
  - Config
  - Core
  - HttpServer
  - JwtAuth
  - JwtMiddleware
  - Logger
  - Metrics
  - MetricsServer
  - Persistence
  - Server
  - Store
  - Subscription
  - WebsocketServer

executables:
  icepeak:
    main: Main.hs
    source-dirs: app/Icepeak
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - ! '"-with-rtsopts=-N -I0"'
    dependencies:
    - icepeak

  icepeak-token-gen:
    main: Main.hs
    source-dirs: app/IcepeakTokenGen
    dependencies:
    - icepeak

tests:
  spec:
    main: Spec.hs
    source-dirs: tests
    ghc-options:
    - -Wno-orphans
    dependencies:
    - hspec
    - hspec-core
    - hspec-expectations
    - QuickCheck
    - quickcheck-instances
    - icepeak
